<a href="https://colab.research.google.com/github/hmyrcmn/MachinaLearning/blob/main/DerinOgrenme_PickleSaveUse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
!pip install -–upgrade –no-deps git+git://github.com/Theano/Theano.git

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -–

In [14]:
!pip install -–upgrade keras

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -–

In [15]:
!pip3 install -–upgrade

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -–

In [16]:
import pandas as pd
data=pd.read_csv('/content/Churn_Modelling.csv')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [17]:
data.head()
#verinin ilk 5 değeri

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [18]:
data.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [19]:
data.shape
#verinin boyutunun öğrenilmesi
# metadata (veriye ait veri )

(10000, 14)

In [20]:
#veride null degerler varmı nasıl kodntrol edili
cauntNull=data.isnull().sum()
print(cauntNull)

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [21]:
x=data.iloc[:,3:13]
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [22]:
x=data.iloc[:,3:13].values # verilerdeki ilk 3 öznitelik (RowNumber	CustomerId	Surname) ayırt edildi model başarısını olumsuz etkilememesi için : burada sensörlerin ıd gibi degerler olursa projede onlar drop edilmeli
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [23]:
y=data.iloc[:,13:].values#y bagımlı değişken .
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [24]:
from sklearn import preprocessing

le =preprocessing.LabelEncoder()

x[:,1]=le.fit_transform(x[:,1]) #kategorik değişken olan georapy sayısal bir değere dönüştürüldü
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [25]:
le2 =preprocessing.LabelEncoder()

x[:,2]=le2.fit_transform(x[:,2]) #kategorik değişken olan cinsiyet  sayısal bir değere dönüştürüldü kadın 0 erkek 1 olarak düzenlendi
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [26]:
# one hot encoding ile 0 1 2 degerlerine dönüştürülen kategorik değişken 0 -1 ile temsil edilir .
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

ohe=ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(sparse=False, dtype=float), [1])],
    remainder='passthrough'
)

x=ohe.fit_transform(x)
x[:,1]

x

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

kategorik verileri  ülke tr fr us ın işlenebilecek formata dönüştüürlülmesi

In [27]:
#eğitim ve test verilerinin oluştrulması
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)

x_train

array([[1.0, 0.0, 0.0, ..., 0, 0, 163112.9],
       [1.0, 0.0, 0.0, ..., 1, 1, 74275.08],
       [1.0, 0.0, 0.0, ..., 0, 1, 62810.91],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

In [28]:
x_test

array([[0.0, 1.0, 0.0, ..., 1, 1, 192852.67],
       [1.0, 0.0, 0.0, ..., 1, 0, 128702.1],
       [0.0, 0.0, 1.0, ..., 1, 1, 75732.25],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 0, 120284.67],
       [0.0, 1.0, 0.0, ..., 0, 0, 125140.72],
       [1.0, 0.0, 0.0, ..., 0, 1, 192131.77]], dtype=object)

In [29]:
y_train

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [30]:
y_test

array([[0],
       [1],
       [0],
       ...,
       [0],
       [1],
       [0]])

ÖZNİTEKİL ÖLÇEKLEME

In [31]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

X_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)

yapay sinir ağı oluşturma

In [32]:
import keras

#yağay sinir ağı oluştur komutu veriliyor keras a
from keras.models import Sequential

#katman oluştruma
from keras.layers import Dense

classifier=Sequential() # yapay sinir ağı oluşturuldu içi boş
# 6 nöron ve 11 nöron girişinden oluşan katman eklendi
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim=12))
  # kaç tane gizli katman veirleceği :32   11+1/2 = 6  ,nput +output

# 2 gizli katman
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))


# çıkış katmanı
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))


#optimizasyon :
#binary kullanılacak bagımsız değişken 0 1 den oluşuyor
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

#adam sdg :veri kümesini küçük parçalara (minibatch) bölmek ve her minibatch için gradyan hesaplamalarını yapmaktır.

In [33]:
# noron network çalıştırma
classifier.fit(X_train, y_train, epochs=50)
# kaç aşamada tekrar edileceğini eposchi belirler

y_pred=classifier.predict(X_test)
y_pred

Epoch 1/50
210/210 [==============================] - 7s 4ms/step - loss: 0.6659 - accuracy: 0.7940
Epoch 2/50
210/210 [==============================] - 1s 4ms/step - loss: 0.6183 - accuracy: 0.7979
Epoch 3/50
210/210 [==============================] - 1s 4ms/step - loss: 0.5760 - accuracy: 0.8091
Epoch 4/50
210/210 [==============================] - 1s 4ms/step - loss: 0.5381 - accuracy: 0.8255
Epoch 5/50
210/210 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.8287
Epoch 6/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4871 - accuracy: 0.8351
Epoch 7/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.8321
Epoch 8/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4572 - accuracy: 0.8348
Epoch 9/50
210/210 [==============================] - 1s 5ms/step - loss: 0.4474 - accuracy: 0.8337
Epoch 10/50
210/210 [==============================] - 1s 5ms/step - loss: 0.4390 - accuracy: 0.8367
Epoch 11/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4322 - accuracy: 0.8372
Epoch 12/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4261 - accuracy: 0.8372
Epoch 13/50
210/210 [==============================] - 1s 5ms/step - loss: 0.4207 - accuracy: 0.8385
Epoch 14/50
210/210 [==============================] - 1s 5ms/step - loss: 0.4156 - accuracy: 0.8396
Epoch 15/50
210/210 [==============================] - 1s 5ms/step - loss: 0.4111 - accuracy: 0.8394
Epoch 16/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4073 - accuracy: 0.8410
Epoch 17/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4043 - accuracy: 0.8427
Epoch 18/50
210/210 [==============================] - 1s 3ms/step - loss: 0.3997 - accuracy: 0.8437
Epoch 19/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3949 - accuracy: 0.8454
Epoch 20/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3884 - accuracy: 0.8506
Epoch 21/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3834 - accuracy: 0.8522
Epoch 22/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3779 - accuracy: 0.8536
Epoch 23/50
210/210 [==============================] - 1s 5ms/step - loss: 0.3720 - accuracy: 0.8560
Epoch 24/50
210/210 [==============================] - 1s 5ms/step - loss: 0.3672 - accuracy: 0.8564
Epoch 25/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3621 - accuracy: 0.8633
Epoch 26/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3571 - accuracy: 0.8599
Epoch 27/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3533 - accuracy: 0.8625
Epoch 28/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3502 - accuracy: 0.8625
Epoch 29/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3474 - accuracy: 0.8639
Epoch 30/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3459 - accuracy: 0.8646
Epoch 31/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3443 - accuracy: 0.8666
Epoch 32/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3438 - accuracy: 0.8648
Epoch 33/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3429 - accuracy: 0.8643
Epoch 34/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3420 - accuracy: 0.8648
Epoch 35/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3415 - accuracy: 0.8646
Epoch 36/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3409 - accuracy: 0.8639
Epoch 37/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3406 - accuracy: 0.8645
Epoch 38/50
210/210 [==============================] - 1s 5ms/step - loss: 0.3402 - accuracy: 0.8652
Epoch 39/50
210/210 [==============================] - 1s 5ms/step - loss: 0.3398 - accuracy: 0.8648
Epoch 40/50
210/210 [==============================] - 1s 5ms/step - loss: 0.3393 - accuracy: 0.8646
Epoch 41/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3393 - accuracy: 0.8651
Epoch 42/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3387 - accuracy: 0.8660
Epoch 43/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3385 - accuracy: 0.8645
Epoch 44/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3382 - accuracy: 0.8649
Epoch 45/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3379 - accuracy: 0.8654
Epoch 46/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3375 - accuracy: 0.8657
Epoch 47/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3380 - accuracy: 0.8651
Epoch 48/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3376 - accuracy: 0.8655
Epoch 49/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3378 - accuracy: 0.8637
Epoch 50/50
210/210 [==============================] - 1s 4ms/step - loss: 0.3374 - accuracy: 0.8646
104/104 [==============================] - 0s 2ms/step

array([[0.25297737],
       [0.24951974],
       [0.17201702],
       ...,
       [0.17576478],
       [0.6533469 ],
       [0.04572802]], dtype=float32)

In [34]:
y_pred=(y_pred>0.5) # t /f 1/0 0.5 den büyükse true
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [35]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)

cm

array([[2528,   89],
       [ 364,  319]])

In [43]:
import pickle

dosya = "DerinOgrenmeModel.kayit"

# Modeli kaydetme
with open(dosya, "wb") as file:
    pickle.dump(classifier, file)

# Modeli yükleme
with open(dosya, "rb") as file:
    loadedModel = pickle.load(file)

# Tahminlerde bulunma
predictions = loadedModel.predict(X_test)
predictions

104/104 [==============================] - 0s 2ms/step

array([[0.25297737],
       [0.24951974],
       [0.17201702],
       ...,
       [0.17576478],
       [0.6533469 ],
       [0.04572802]], dtype=float32)